package com.kgc.cn.provider.mapper;

import java.util.List;

import com.kgc.cn.common.dto.Userdb;
import com.kgc.cn.common.dto.UserdbExample;
import org.apache.ibatis.annotations.Param;

public interface UserdbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbg.generated
     */
    long countByExample(UserdbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbg.generated
     */
    int deleteByExample(UserdbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbg.generated
     */
    int insert(Userdb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbg.generated
     */
    int insertSelective(Userdb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbg.generated
     */
    List<Userdb> selectByExample(UserdbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbg.generated
     */
    Userdb selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Userdb record, @Param("example") UserdbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Userdb record, @Param("example") UserdbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Userdb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Userdb record);
}