package com.kgc.cn.common.dto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table flashgoods
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Flashgoods implements Serializable {
    private static final long serialVersionUID = 7713514054258935636L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flashgoods.goodsId
     *
     * @mbg.generated
     */
    private Long goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flashgoods.goodsDescription
     *
     * @mbg.generated
     */
    private String goodsdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flashgoods.goodsName
     *
     * @mbg.generated
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flashgoods.goodsColor
     *
     * @mbg.generated
     */
    private String goodscolor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flashgoods.goodsCount
     *
     * @mbg.generated
     */
    private Integer goodscount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flashgoods.goodsId
     *
     * @return the value of flashgoods.goodsId
     *
     * @mbg.generated
     */
    public Long getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flashgoods.goodsId
     *
     * @param goodsid the value for flashgoods.goodsId
     *
     * @mbg.generated
     */
    public void setGoodsid(Long goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flashgoods.goodsDescription
     *
     * @return the value of flashgoods.goodsDescription
     *
     * @mbg.generated
     */
    public String getGoodsdescription() {
        return goodsdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flashgoods.goodsDescription
     *
     * @param goodsdescription the value for flashgoods.goodsDescription
     *
     * @mbg.generated
     */
    public void setGoodsdescription(String goodsdescription) {
        this.goodsdescription = goodsdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flashgoods.goodsName
     *
     * @return the value of flashgoods.goodsName
     *
     * @mbg.generated
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flashgoods.goodsName
     *
     * @param goodsname the value for flashgoods.goodsName
     *
     * @mbg.generated
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flashgoods.goodsColor
     *
     * @return the value of flashgoods.goodsColor
     *
     * @mbg.generated
     */
    public String getGoodscolor() {
        return goodscolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flashgoods.goodsColor
     *
     * @param goodscolor the value for flashgoods.goodsColor
     *
     * @mbg.generated
     */
    public void setGoodscolor(String goodscolor) {
        this.goodscolor = goodscolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flashgoods.goodsCount
     *
     * @return the value of flashgoods.goodsCount
     *
     * @mbg.generated
     */
    public Integer getGoodscount() {
        return goodscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flashgoods.goodsCount
     *
     * @param goodscount the value for flashgoods.goodsCount
     *
     * @mbg.generated
     */
    public void setGoodscount(Integer goodscount) {
        this.goodscount = goodscount;
    }
}