package com.kgc.cn.common.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table userdb
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Userdb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdb.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdb.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdb.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdb.id
     *
     * @return the value of userdb.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdb.id
     *
     * @param id the value for userdb.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdb.username
     *
     * @return the value of userdb.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdb.username
     *
     * @param username the value for userdb.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdb.password
     *
     * @return the value of userdb.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdb.password
     *
     * @param password the value for userdb.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }
}